### ISSUE TITLE
How does this deal with SSR?

### ISSUE THREAD

**Issue by jaredlll08** [cobraz/nextjs-oidc-react#1]
Hey!
So I'm trying to wrangle my brain around using OIDC and next.js, and I found your repo, I just have one question though, over here:
https://github.com/cobraz/nextjs-oidc-react/blob/master/pages/index.tsx#L5
So from what I understand, you are disabling SSR, so everything is rendered on the client.

So does using this as a prototype effectively make it that no pages that require any auth stuff (even something like showing the logged in user's username on the navbar) can be SSR?

Thanks!

**Comment by cobraz** [comment]
Honestly, I don't know.

I'm wondering if everything under the `<AuthProvider />` would also be without SSR. I'll have to check :)
Let me know if you end up with an answer :)

**Comment by cobraz** [comment]
Did you check it out, @jaredlll08 ? :)

**Comment by jaredlll08** [comment]
So I checked it out, and from the looks of it, and from what I understand of this:
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr
Anything under `AuthProvider` won't be SSR, so probably best not to have the full app under it (unless you are fine without SSR)

**Comment by cobraz** [comment]
Thanks for the feedback!

**Comment by cobraz** [comment]
I'm thinking of researching this some more, and see how things can be changed in order to still have SSR.
